-- =============================================================================
-- sample05.sql  -  Production report: page template, header, footer, save
-- =============================================================================
--
-- WHAT THIS SHOWS
--   • rad_pdf_types.t_page_template - assigns margin overrides AND embeds the
--     header/footer PL/SQL code that runs on every page
--   • header_proc / footer_proc - anonymous PL/SQL blocks (BEGIN...END;),
--     stored as VARCHAR2 and executed by EXECUTE IMMEDIATE AFTER the render
--     pass, so they can reference the final #PAGE_COUNT# value
--   • Tokens replaced at runtime:
--       #DOC_HANDLE#   - document handle integer (lets the block call
--                         rad_pdf_canvas.* without knowing the handle value)
--       #PAGE_NR#      - current page number, 1-based
--       #PAGE_COUNT#   - total number of pages in the document
--   • rad_pdf.save() - writes the PDF directly to an Oracle Directory object
--                  instead of returning a BLOB
--
-- PAGE TEMPLATE MECHANICS
--   When you pass p_template to new_document, the layout engine reserves the
--   margin_top and margin_bottom space on every page for your header/footer.
--   The body content (headings, text, tables) flows only within the printable
--   area between those margins.  You use rad_pdf_canvas.* calls inside the proc
--   strings to draw into the reserved zones.
--
--   The header_proc and footer_proc strings are double-quoted PL/SQL literals,
--   so single quotes inside must be doubled: '' (two single quotes = one quote).
--
-- TO SAVE TO A FILE (Option B)
--   Requires an Oracle Directory object pointing to a writable OS path.
--   Run once as DBA:
--     CREATE OR REPLACE DIRECTORY PDF_OUT AS '/tmp/rad_pdf';
--     GRANT WRITE ON DIRECTORY PDF_OUT TO <your_schema>;
--   Then uncomment the rad_pdf.save() call and comment out finalize().
--
-- HOW TO RUN
--   Same as sample01.sql - see its header for other output options.
-- =============================================================================

SET SERVEROUTPUT ON

DECLARE
  l_doc  rad_pdf_types.t_doc_handle;
  l_info rad_pdf_types.t_doc_info;
  l_tpl  rad_pdf_types.t_page_template;
  l_cols rad_pdf_types.t_columns;
  l_clr  rad_pdf_types.t_color_scheme;
  l_pdf  BLOB;
BEGIN
  rad_pdf_styles.load_defaults;

  -- =========================================================================
  -- Page template
  -- A4 portrait height is 842 pt.  Increase top margin so the layout engine
  -- leaves a ~30 pt header zone above y ≈ 810.
  -- =========================================================================
  l_tpl.page_format_name := 'A4';
  l_tpl.margin_top       := 70;    -- body area starts at ~772 pt from bottom
  l_tpl.margin_bottom    := 50;    -- footer zone below ~50 pt
  l_tpl.margin_left      := 42;
  l_tpl.margin_right     := 42;

  -- =========================================================================
  -- Header procedure
  -- Executed once per page after the layout pass completes.
  -- Draws: company label (navy bold, top-left) + page number (right) + line.
  -- The double-single-quote ('') inside the concatenated string is the Oracle
  -- way to embed a single quote inside a string literal.
  -- =========================================================================
  l_tpl.header_proc :=
    'BEGIN ' ||
      -- Company / report name at top-left in navy bold
      'rad_pdf_canvas.set_font (#DOC_HANDLE#, ''Helvetica'', ''B'', 9); ' ||
      'rad_pdf_canvas.set_color(#DOC_HANDLE#, ''003366''); ' ||
      'rad_pdf_canvas.write_text(#DOC_HANDLE#, ' ||
        '''Monthly Sales Report - Confidential'', 42, 818, ''pt''); ' ||
      -- Page n / total at top-right in normal weight
      'rad_pdf_canvas.set_color(#DOC_HANDLE#, ''000000''); ' ||
      'rad_pdf_canvas.set_font (#DOC_HANDLE#, ''Helvetica'', ''N'', 9); ' ||
      'rad_pdf_canvas.write_text(#DOC_HANDLE#, ' ||
        '''Page #PAGE_NR# / #PAGE_COUNT#'', 490, 818, ''pt''); ' ||
      -- Thin navy separator line below the header text
      'rad_pdf_canvas.h_line(#DOC_HANDLE#, 42, 810, 511, 0.4, ''003366'', ''pt''); ' ||
    'END;';

  -- =========================================================================
  -- Footer procedure
  -- Draws a thin grey line at y=42, then an italic generator notice.
  -- =========================================================================
  l_tpl.footer_proc :=
    'BEGIN ' ||
      'rad_pdf_canvas.h_line(#DOC_HANDLE#, 42, 42, 511, 0.4, ''808080'', ''pt''); ' ||
      'rad_pdf_canvas.set_font (#DOC_HANDLE#, ''Helvetica'', ''I'', 8); ' ||
      'rad_pdf_canvas.set_color(#DOC_HANDLE#, ''808080''); ' ||
      'rad_pdf_canvas.write_text(#DOC_HANDLE#, ' ||
        '''Generated by RAD_PDF on Oracle Database'', 42, 28, ''pt''); ' ||
    'END;';

  -- =========================================================================
  -- Document metadata
  -- keywords appear in PDF viewer File → Properties → Keywords field
  -- =========================================================================
  l_info.title    := 'Monthly Sales Report';
  l_info.author   := 'Sales Analytics';
  l_info.subject  := 'Revenue by Region';
  l_info.keywords := 'sales report revenue region Q1 2026';

  -- =========================================================================
  -- Column definitions - four columns; total ~390 pt
  -- =========================================================================
  l_cols := rad_pdf_types.t_columns();
  l_cols.EXTEND(4);

  l_cols(1).label              := 'Region';
  l_cols(1).width              := 130;

  l_cols(2).label              := 'Deals';
  l_cols(2).width              := 60;
  l_cols(2).data_fmt.align_h   := 'R';
  l_cols(2).header_fmt.align_h := 'C';

  l_cols(3).label              := 'Revenue ($K)';
  l_cols(3).width              := 110;
  l_cols(3).data_fmt.align_h   := 'R';
  l_cols(3).header_fmt.align_h := 'C';
  l_cols(3).data_fmt.num_format := 'FM999,990.0';

  l_cols(4).label              := 'YoY Change';
  l_cols(4).width              := 90;
  l_cols(4).data_fmt.align_h   := 'C';
  l_cols(4).header_fmt.align_h := 'C';

  -- Start from the default scheme; override only the header colors.
  l_clr := rad_pdf_styles.default_scheme;
  l_clr.header_paper := '003366';
  l_clr.header_ink   := 'FFFFFF';

  -- =========================================================================
  -- Build document - pass the template so it applies to every page
  -- =========================================================================
  l_doc := rad_pdf.new_document(p_info => l_info, p_template => l_tpl);

  rad_pdf.heading(l_doc, 'Monthly Sales Report', 1);
  rad_pdf.heading(l_doc, 'Revenue by Region - Q1 2026', 2);
  rad_pdf.write  (l_doc,
    'The following table summarises closed deals and revenue per region for the ' ||
    'first quarter of 2026. Figures are in thousands of USD.');
  rad_pdf.spacer (l_doc, 8);

  rad_pdf.query2table(l_doc,
    'SELECT region, deals, revenue, yoy_change FROM (' ||
    '  SELECT ''North America'' region,  42 deals, 1820.5 revenue, ''+12%'' yoy_change FROM DUAL UNION ALL ' ||
    '  SELECT ''EMEA'',                  38,        1540.0,         ''+18%''                FROM DUAL UNION ALL ' ||
    '  SELECT ''APAC'',                  29,        1120.3,         ''+24%''                FROM DUAL UNION ALL ' ||
    '  SELECT ''Latin America'',         17,         430.8,         ''+9%''                 FROM DUAL UNION ALL ' ||
    '  SELECT ''Middle East & Africa'',  11,         280.1,         ''+31%''                FROM DUAL' ||
    ')',
    l_cols,
    p_colors => l_clr);

  rad_pdf.spacer(l_doc, 12);
  rad_pdf.add   (l_doc, rad_pdf_layout.h_rule('003366', 1));
  rad_pdf.spacer(l_doc, 6);
  rad_pdf.write (l_doc,
    'Total Q1 2026 revenue: $5,191.7K  |  Total deals closed: 137  |  ' ||
    'Overall YoY growth: +17.4%', 'caption');

  -- =========================================================================
  -- Output - choose one option:
  -- =========================================================================

  -- Option A (default): return as BLOB for testing or SQL Developer preview
  l_pdf := rad_pdf.finalize(l_doc);
  DBMS_OUTPUT.PUT_LINE('PDF generated - size: ' || DBMS_LOB.GETLENGTH(l_pdf) || ' bytes');
  -- :rad_pdf := l_pdf;   -- uncomment to expose as SQL Developer bind variable
  DBMS_LOB.FREETEMPORARY(l_pdf);

  -- Option B: save directly to an Oracle Directory (see prerequisites above)
  -- Replace finalize/FREETEMPORARY above with:
  -- rad_pdf.save(l_doc, 'PDF_OUT', 'monthly_sales_q1_2026.rad_pdf');
END;
/
