-- =============================================================================
-- sample02.sql  -  Styled report: headings, body text, custom styles
-- =============================================================================
--
-- WHAT THIS SHOWS
--   • Heading levels h1 and h2 (built-in styles)
--   • Body paragraphs with automatic word-wrap
--   • A custom style defined at runtime (rad_pdf_styles.define)
--   • Spacers and a horizontal rule to separate sections
--   • An explicit page break (rad_pdf.new_page)
--   • Document metadata embedded in the PDF (title, author, subject)
--
-- HOW TO RUN
--   Same as sample01.sql - see its header for save/download options.
--
-- WHAT TO EXPECT
--   A two-page PDF.  Page 1: large heading, two sections, grey divider.
--   Page 2: new heading after the explicit break.
-- =============================================================================

SET SERVEROUTPUT ON

DECLARE
  l_doc  rad_pdf_types.t_doc_handle;
  l_info rad_pdf_types.t_doc_info;   -- document metadata (shown in PDF viewer File → Properties)
  l_pdf  BLOB;
BEGIN
  -- -------------------------------------------------------------------------
  -- Session setup: load built-in styles (once per session is enough)
  -- -------------------------------------------------------------------------
  rad_pdf_styles.load_defaults;

  -- -------------------------------------------------------------------------
  -- Define a custom style.
  -- rad_pdf_styles.define() is idempotent - safe to call on every run.
  -- Parameters not supplied inherit from the 'default' style.
  -- -------------------------------------------------------------------------
  rad_pdf_styles.define(
    p_name       => 'notice',      -- name used later in rad_pdf.write()
    p_font_name  => 'Helvetica',
    p_font_style => 'BI',          -- Bold-Italic
    p_font_size  => 10,
    p_font_color => 'CC3300'       -- dark red; always 6-char hex RGB
  );

  -- -------------------------------------------------------------------------
  -- Document metadata - appears in File → Properties in PDF viewers
  -- -------------------------------------------------------------------------
  l_info.title   := 'Quarterly Report Q1 2026';
  l_info.author  := 'Finance Department';
  l_info.subject := 'Revenue and Operations Summary';

  l_doc := rad_pdf.new_document(p_info => l_info);

  -- =========================================================================
  -- PAGE 1
  -- =========================================================================

  -- h1: Helvetica Bold 18 pt (built-in 'h1' style)
  rad_pdf.heading(l_doc, 'Quarterly Report - Q1 2026', 1);

  -- h2: Helvetica Bold 16 pt (built-in 'h2' style)
  rad_pdf.heading(l_doc, 'Executive Summary', 2);

  -- Body paragraph - text wraps automatically when wider than the printable area
  rad_pdf.write(l_doc,
    'Revenue for Q1 2026 reached $4.2 M, an 18% increase year-over-year. ' ||
    'Operating costs decreased by 6% due to process automation initiatives.');

  rad_pdf.spacer(l_doc, 10);   -- 10-point vertical gap

  -- Write with the custom 'notice' style
  rad_pdf.write(l_doc,
    'NET PROFIT MARGIN: 23% - above the 20% annual target.',
    'notice');

  rad_pdf.spacer(l_doc, 8);

  -- Horizontal rule: rad_pdf_layout.h_rule(color_hex, thickness_pt)
  -- rad_pdf.add() accepts any flowable built by rad_pdf_layout.*
  rad_pdf.add(l_doc, rad_pdf_layout.h_rule('808080', 0.5));

  rad_pdf.spacer(l_doc, 8);

  rad_pdf.heading(l_doc, 'Regional Breakdown', 2);
  rad_pdf.write(l_doc,
    'EMEA contributed 41% of total revenue, up from 37% in Q4 2025. ' ||
    'APAC growth was 24%, driven by new enterprise contracts in Japan and Australia.');

  -- =========================================================================
  -- PAGE BREAK - everything after this starts on a new page
  -- In layout mode, rad_pdf.new_page() inserts a page-break flowable.
  -- The engine places it precisely when rendering.
  -- =========================================================================
  rad_pdf.new_page(l_doc);

  -- =========================================================================
  -- PAGE 2
  -- =========================================================================
  rad_pdf.heading(l_doc, 'Outlook', 2);
  rad_pdf.write(l_doc,
    'Q2 2026 forecast: $4.6 M revenue with continued margin expansion. ' ||
    'Three new product lines are scheduled for May release.');

  -- 'caption' is a built-in style: Helvetica Italic 8 pt, grey
  rad_pdf.write(l_doc, 'Report generated by RAD_PDF.', 'caption');

  -- =========================================================================
  -- Finalise
  -- =========================================================================
  l_pdf := rad_pdf.finalize(l_doc);

  DBMS_OUTPUT.PUT_LINE('PDF generated - size: ' || DBMS_LOB.GETLENGTH(l_pdf) || ' bytes');
  -- :rad_pdf := l_pdf;
  DBMS_LOB.FREETEMPORARY(l_pdf);
END;
/
